runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 6.1
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
liveness_check:
  path: "/"
readiness_check:
  path: "/"
